export interface PDFLeadRecord {
  id: string;
  company_name: string;
  website?: string;
  linkedin_url?: string;
  employee_count?: string;
  industry?: string;
  hr_name: string;
  title: string;
  phone?: string;
  email?: string;
  hr_linkedin?: string;
  domain: string;
  location: string;
  remarks: string;
  spoc: string; // Sheet owner: 'Namitha' | 'Aliya' | 'Solomon' | 'Harish' | 'Varshith' | 'Aasritha' | 'Charan'
  entered_by_name: string;
}

export const INITIAL_PDF_LEADS: PDFLeadRecord[] = [
  // --- NAMITHA'S SHEET ---
  {
    id: 'lead_namitha_1',
    company_name: 'Adrosonic IT Solutions',
    website: 'https://adrosonic.com',
    linkedin_url: 'https://www.linkedin.com/company/adrosonic',
    employee_count: '250-500 employees',
    industry: 'Cyber Security & Digital Transformation',
    hr_name: 'Anjali Sharma',
    title: 'Senior Talent Acquisition Specialist',
    phone: '+91 98201 44321',
    email: 'anjali.s@adrosonic.com',
    hr_linkedin: 'https://www.linkedin.com/in/anjali-sharma-adrosonic',
    domain: 'Cyber Security',
    location: 'Mumbai / Hyderabad',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_2',
    company_name: 'Auctor Infometrics Pvt Ltd',
    website: 'https://auctor.in',
    linkedin_url: 'https://www.linkedin.com/company/auctor-infometrics',
    employee_count: '100-250 employees',
    industry: 'Enterprise Security & IT Services',
    hr_name: 'Pooja Verma',
    title: 'HR Manager - Talent Sourcing',
    phone: '+91 97112 55890',
    email: 'pooja.v@auctor.in',
    hr_linkedin: 'https://www.linkedin.com/in/pooja-verma-auctor',
    domain: 'Cyber Security',
    location: 'Noida / Remote',
    remarks: 'Mail Sent',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_3',
    company_name: 'Canonic Security',
    website: 'https://canonic.com',
    linkedin_url: 'https://www.linkedin.com/company/canonic-security',
    employee_count: '50-100 employees',
    industry: 'SaaS App Security',
    hr_name: 'Rohan Nambiar',
    title: 'Lead Technical Recruiter',
    phone: '+91 99803 11244',
    email: 'rohan.n@canonic.com',
    hr_linkedin: 'https://www.linkedin.com/in/rohan-nambiar-canonic',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_4',
    company_name: 'Claroty Networks India',
    website: 'https://claroty.com',
    linkedin_url: 'https://www.linkedin.com/company/claroty',
    employee_count: '500-1,000 employees',
    industry: 'Industrial & IoT Cyber Security',
    hr_name: 'Divya Nair',
    title: 'Talent Acquisition Partner',
    phone: '+91 98450 78219',
    email: 'divya.n@claroty.com',
    hr_linkedin: 'https://www.linkedin.com/in/divya-nair-claroty',
    domain: 'Cyber Security',
    location: 'Hyderabad / Pune',
    remarks: 'Hold',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_5',
    company_name: 'Cyberhaven Security India',
    website: 'https://cyberhaven.com',
    linkedin_url: 'https://www.linkedin.com/company/cyberhaven',
    employee_count: '250-500 employees',
    industry: 'Data Detection and Response (DDR)',
    hr_name: 'Kavitha R',
    title: 'HR Operations & Sourcing',
    phone: '+91 97401 33201',
    email: 'kavitha.r@cyberhaven.com',
    hr_linkedin: 'https://www.linkedin.com/in/kavitha-cyberhaven',
    domain: 'Cyber Security',
    location: 'Bengaluru / Remote',
    remarks: 'Not Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_6',
    company_name: 'Cyware Labs India',
    website: 'https://cyware.com',
    linkedin_url: 'https://www.linkedin.com/company/cyware-labs',
    employee_count: '250-500 employees',
    industry: 'Cyber Threat Intelligence & Orchestration',
    hr_name: 'Suresh Menon',
    title: 'Senior HR Specialist',
    phone: '+91 99008 67451',
    email: 'suresh.m@cyware.com',
    hr_linkedin: 'https://www.linkedin.com/in/suresh-menon-cyware',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_7',
    company_name: 'DigiGlass by Minfy',
    website: 'https://minfytech.com/digiglass',
    linkedin_url: 'https://www.linkedin.com/company/digiglass-minfy',
    employee_count: '500-1,000 employees',
    industry: 'Managed Security Services (MSSP)',
    hr_name: 'Sneha Kulkarni',
    title: 'Campus & Lateral Recruiter',
    phone: '+91 96190 22345',
    email: 'sneha.k@minfytech.com',
    hr_linkedin: 'https://www.linkedin.com/in/sneha-digiglass',
    domain: 'Cyber Security',
    location: 'Hyderabad',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_8',
    company_name: 'Forcepoint Security Solutions',
    website: 'https://forcepoint.com',
    linkedin_url: 'https://www.linkedin.com/company/forcepoint',
    employee_count: '2,000-5,000 employees',
    industry: 'User and Data Protection Cloud Security',
    hr_name: 'Manoj Kumar Panda',
    title: 'Head of Talent Acquisition',
    phone: '+91 98801 99872',
    email: 'manoj.panda@forcepoint.com',
    hr_linkedin: 'https://www.linkedin.com/in/manoj-panda-forcepoint',
    domain: 'Cyber Security',
    location: 'Bengaluru / Hyderabad',
    remarks: 'No Hirings',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_9',
    company_name: 'Glavisco Solutions',
    website: 'https://glavisco.com',
    linkedin_url: 'https://www.linkedin.com/company/glavisco',
    employee_count: '50-100 employees',
    industry: 'SOC Operations & Vulnerability Assessment',
    hr_name: 'Neha Roy',
    title: 'HR Executive',
    phone: '+91 98310 44512',
    email: 'neha.r@glavisco.com',
    hr_linkedin: 'https://www.linkedin.com/in/neha-roy-glavisco',
    domain: 'Cyber Security',
    location: 'Kolkata / Remote',
    remarks: 'Pending',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_10',
    company_name: 'Kaseya Technologies',
    website: 'https://kaseya.com',
    linkedin_url: 'https://www.linkedin.com/company/kaseya',
    employee_count: '5,000-10,000 employees',
    industry: 'IT Infrastructure & Security Management',
    hr_name: 'Arun Balakrishnan',
    title: 'Staff Recruiter',
    phone: '+91 99400 11983',
    email: 'arun.b@kaseya.com',
    hr_linkedin: 'https://www.linkedin.com/in/arun-kaseya',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_11',
    company_name: 'Micro Focus (OpenText)',
    website: 'https://opentext.com',
    linkedin_url: 'https://www.linkedin.com/company/opentext',
    employee_count: '10,000+ employees',
    industry: 'Enterprise Software & Cyber Resilience',
    hr_name: 'Shruti Hegde',
    title: 'Talent Acquisition Leader',
    phone: '+91 98455 33210',
    email: 'shruti.hegde@opentext.com',
    hr_linkedin: 'https://www.linkedin.com/in/shruti-hegde-opentext',
    domain: 'Cyber Security',
    location: 'Bengaluru / Pune',
    remarks: 'Hold',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },
  {
    id: 'lead_namitha_12',
    company_name: 'Morphisec India',
    website: 'https://morphisec.com',
    linkedin_url: 'https://www.linkedin.com/company/morphisec',
    employee_count: '100-250 employees',
    industry: 'Automated Moving Target Defense (AMTD)',
    hr_name: 'Deepak Varma',
    title: 'Senior Recruiter',
    phone: '+91 97411 90812',
    email: 'deepak.v@morphisec.com',
    hr_linkedin: 'https://www.linkedin.com/in/deepak-varma-morphisec',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Namitha',
    entered_by_name: 'Namitha K',
  },

  // --- ALIYA'S SHEET ---
  {
    id: 'lead_aliya_1',
    company_name: 'Netrika Consulting India',
    website: 'https://netrika.com',
    linkedin_url: 'https://www.linkedin.com/company/netrika-consulting',
    employee_count: '250-500 employees',
    industry: 'Risk Mitigation & Cyber Forensics',
    hr_name: 'Shreya Kapoor',
    title: 'Head of Human Resources',
    phone: '+91 98101 22910',
    email: 'shreya.k@netrika.com',
    hr_linkedin: 'https://www.linkedin.com/in/shreya-kapoor-netrika',
    domain: 'Cyber Security',
    location: 'Gurugram / Mumbai',
    remarks: 'Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_2',
    company_name: 'Securonix India Pvt Ltd',
    website: 'https://securonix.com',
    linkedin_url: 'https://www.linkedin.com/company/securonix',
    employee_count: '1,000-2,000 employees',
    industry: 'Next-Gen SIEM & Threat Intelligence',
    hr_name: 'Preeti Deshmukh',
    title: 'HR Director - APAC',
    phone: '+91 98230 77142',
    email: 'preeti.d@securonix.com',
    hr_linkedin: 'https://www.linkedin.com/in/preeti-deshmukh-securonix',
    domain: 'Cyber Security',
    location: 'Pune / Bengaluru',
    remarks: 'Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_3',
    company_name: 'SecurityHQ India',
    website: 'https://securityhq.com',
    linkedin_url: 'https://www.linkedin.com/company/securityhq',
    employee_count: '500-1,000 employees',
    industry: 'Global Managed Detection & Response (MDR)',
    hr_name: 'Aditi Joshi',
    title: 'Lead Talent Sourcing Manager',
    phone: '+91 96541 88203',
    email: 'aditi.j@securityhq.com',
    hr_linkedin: 'https://www.linkedin.com/in/aditi-joshi-securityhq',
    domain: 'Cyber Security',
    location: 'Pune / Noida',
    remarks: 'Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_4',
    company_name: 'Tanium Technologies India',
    website: 'https://tanium.com',
    linkedin_url: 'https://www.linkedin.com/company/tanium',
    employee_count: '2,000-5,000 employees',
    industry: 'Converged Endpoint Management (XEM)',
    hr_name: 'Rajesh Goud',
    title: 'Senior Technical Recruiter',
    phone: '+91 99490 66219',
    email: 'rajesh.goud@tanium.com',
    hr_linkedin: 'https://www.linkedin.com/in/rajesh-goud-tanium',
    domain: 'Cyber Security',
    location: 'Bengaluru / Hyderabad',
    remarks: 'Hold',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_5',
    company_name: 'ThreatConnect Solutions',
    website: 'https://threatconnect.com',
    linkedin_url: 'https://www.linkedin.com/company/threatconnect',
    employee_count: '250-500 employees',
    industry: 'Threat Intelligence Operations & SOAR',
    hr_name: 'Fatima Zohra',
    title: 'Recruitment Consultant',
    phone: '+91 98402 11984',
    email: 'fatima.z@threatconnect.com',
    hr_linkedin: 'https://www.linkedin.com/in/fatima-zohra-threatconnect',
    domain: 'Cyber Security',
    location: 'Chennai / Remote',
    remarks: 'Mail Sent',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_6',
    company_name: 'Varonis Systems India',
    website: 'https://varonis.com',
    linkedin_url: 'https://www.linkedin.com/company/varonis',
    employee_count: '2,000-5,000 employees',
    industry: 'Data Security Posture Management (DSPM)',
    hr_name: 'Meenakshi Iyer',
    title: 'Talent Acquisition Specialist',
    phone: '+91 98840 55192',
    email: 'meenakshi.i@varonis.com',
    hr_linkedin: 'https://www.linkedin.com/in/meenakshi-varonis',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_7',
    company_name: 'WiJungle (Cyber Horizon)',
    website: 'https://wijungle.com',
    linkedin_url: 'https://www.linkedin.com/company/wijungle',
    employee_count: '100-250 employees',
    industry: 'Unified Network Security & UTM',
    hr_name: 'Karmesh Gupta',
    title: 'VP People & Operations',
    phone: '+91 98290 12340',
    email: 'karmesh.g@wijungle.com',
    hr_linkedin: 'https://www.linkedin.com/in/karmesh-gupta-wijungle',
    domain: 'Cyber Security',
    location: 'Jaipur / Gurugram',
    remarks: 'Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },
  {
    id: 'lead_aliya_8',
    company_name: 'Zimperium Mobile Defense',
    website: 'https://zimperium.com',
    linkedin_url: 'https://www.linkedin.com/company/zimperium',
    employee_count: '250-500 employees',
    industry: 'Mobile Application & Device Security',
    hr_name: 'Pratik Solanki',
    title: 'Senior HR Recruiter',
    phone: '+91 99250 88123',
    email: 'pratik.s@zimperium.com',
    hr_linkedin: 'https://www.linkedin.com/in/pratik-solanki-zimperium',
    domain: 'Cyber Security',
    location: 'Bengaluru / Ahmedabad',
    remarks: 'Not Responded',
    spoc: 'Aliya',
    entered_by_name: 'Aliya Shaik',
  },

  // --- SOLOMON'S SHEET ---
  {
    id: 'lead_solomon_1',
    company_name: 'Acalvio Technologies',
    website: 'https://acalvio.com',
    linkedin_url: 'https://www.linkedin.com/company/acalvio-technologies',
    employee_count: '100-250 employees',
    industry: 'Autonomous Cyber Deception & AI',
    hr_name: 'Sunil Rao',
    title: 'Head of Recruitment',
    phone: '+91 98451 90901',
    email: 'sunil.r@acalvio.com',
    hr_linkedin: 'https://www.linkedin.com/in/sunil-rao-acalvio',
    domain: 'Gen AI & Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_2',
    company_name: 'Akira Technologies',
    website: 'https://akiratech.com',
    linkedin_url: 'https://www.linkedin.com/company/akira-tech',
    employee_count: '50-100 employees',
    industry: 'AI Defense Solutions & SOC Monitoring',
    hr_name: 'Tanya Sengupta',
    title: 'HR Business Partner',
    phone: '+91 98305 66710',
    email: 'tanya.s@akiratech.com',
    hr_linkedin: 'https://www.linkedin.com/in/tanya-akira',
    domain: 'Gen AI',
    location: 'Kolkata / Hyderabad',
    remarks: 'Mail Sent',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_3',
    company_name: 'Appknox (XYSEC Labs)',
    website: 'https://appknox.com',
    linkedin_url: 'https://www.linkedin.com/company/appknox',
    employee_count: '100-250 employees',
    industry: 'Automated Mobile Security & Pentesting',
    hr_name: 'Subhojit Mukherjee',
    title: 'Lead Talent Scout',
    phone: '+91 97312 44901',
    email: 'subhojit@appknox.com',
    hr_linkedin: 'https://www.linkedin.com/in/subhojit-appknox',
    domain: 'Cyber Security',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_4',
    company_name: 'Bishop Fox Security',
    website: 'https://bishopfox.com',
    linkedin_url: 'https://www.linkedin.com/company/bishop-fox',
    employee_count: '500-1,000 employees',
    industry: 'Offensive Security & Red Teaming',
    hr_name: 'Archana Gowda',
    title: 'Global Talent Recruiter',
    phone: '+91 99011 22894',
    email: 'archana.g@bishopfox.com',
    hr_linkedin: 'https://www.linkedin.com/in/archana-gowda-bishopfox',
    domain: 'Cyber Security',
    location: 'Bengaluru / Remote',
    remarks: 'Hold',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_5',
    company_name: 'Cato Networks India',
    website: 'https://catonetworks.com',
    linkedin_url: 'https://www.linkedin.com/company/cato-networks',
    employee_count: '1,000-2,000 employees',
    industry: 'SASE (Secure Access Service Edge)',
    hr_name: 'Laxman Prasad',
    title: 'Director - India HR',
    phone: '+91 98490 88231',
    email: 'laxman.p@catonetworks.com',
    hr_linkedin: 'https://www.linkedin.com/in/laxman-prasad-cato',
    domain: 'Cyber Security',
    location: 'Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_6',
    company_name: 'Checkmarx India Pvt Ltd',
    website: 'https://checkmarx.com',
    linkedin_url: 'https://www.linkedin.com/company/checkmarx',
    employee_count: '1,000-2,000 employees',
    industry: 'Application Security Testing (AST)',
    hr_name: 'Pallavi Shinde',
    title: 'Senior Recruiter',
    phone: '+91 98220 44590',
    email: 'pallavi.s@checkmarx.com',
    hr_linkedin: 'https://www.linkedin.com/in/pallavi-shinde-checkmarx',
    domain: 'Cyber Security',
    location: 'Pune / Bengaluru',
    remarks: 'No Openings',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },
  {
    id: 'lead_solomon_7',
    company_name: 'Cymulate Threat Simulation',
    website: 'https://cymulate.com',
    linkedin_url: 'https://www.linkedin.com/company/cymulate',
    employee_count: '250-500 employees',
    industry: 'Breach and Attack Simulation (BAS)',
    hr_name: 'Amitabh Sen',
    title: 'India Talent Partner',
    phone: '+91 98110 55672',
    email: 'amitabh.s@cymulate.com',
    hr_linkedin: 'https://www.linkedin.com/in/amitabh-sen-cymulate',
    domain: 'Cyber Security',
    location: 'Delhi NCR / Bengaluru',
    remarks: 'Responded',
    spoc: 'Solomon',
    entered_by_name: 'Solomon Raj',
  },

  // --- HARISH'S SHEET ---
  {
    id: 'lead_harish_1',
    company_name: 'Fractal Analytics',
    website: 'https://fractal.ai',
    linkedin_url: 'https://www.linkedin.com/company/fractal-analytics',
    employee_count: '2,000-5,000 employees',
    industry: 'Artificial Intelligence & Generative AI',
    hr_name: 'Kunal Singhal',
    title: 'Lead AI & GenAI Recruiter',
    phone: '+91 98192 33410',
    email: 'kunal.s@fractal.ai',
    hr_linkedin: 'https://www.linkedin.com/in/kunal-singhal-fractal',
    domain: 'Gen AI',
    location: 'Mumbai / Bengaluru / Gurugram',
    remarks: 'Responded',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },
  {
    id: 'lead_harish_2',
    company_name: 'Mu Sigma Inc',
    website: 'https://mu-sigma.com',
    linkedin_url: 'https://www.linkedin.com/company/mu-sigma',
    employee_count: '2,000-5,000 employees',
    industry: 'Decision Sciences & Big Data Analytics',
    hr_name: 'Swathi Menon',
    title: 'Campus & Early Career Hiring Lead',
    phone: '+91 98450 67123',
    email: 'swathi.m@mu-sigma.com',
    hr_linkedin: 'https://www.linkedin.com/in/swathi-menon-musigma',
    domain: 'Data Science',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },
  {
    id: 'lead_harish_3',
    company_name: 'Tiger Analytics',
    website: 'https://tigeranalytics.com',
    linkedin_url: 'https://www.linkedin.com/company/tiger-analytics',
    employee_count: '2,000-5,000 employees',
    industry: 'AI, Machine Learning & Modern Data Engineering',
    hr_name: 'Naveen Kumar',
    title: 'Principal TA Specialist',
    phone: '+91 98409 88120',
    email: 'naveen.k@tigeranalytics.com',
    hr_linkedin: 'https://www.linkedin.com/in/naveen-kumar-tiger',
    domain: 'Gen AI',
    location: 'Chennai / Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },
  {
    id: 'lead_harish_4',
    company_name: 'LatentView Analytics',
    website: 'https://latentview.com',
    linkedin_url: 'https://www.linkedin.com/company/latentview',
    employee_count: '1,000-2,000 employees',
    industry: 'Digital Analytics & Predictive Modeling',
    hr_name: 'Geetha Ramanathan',
    title: 'Senior Manager - Talent Acquisition',
    phone: '+91 98841 22349',
    email: 'geetha.r@latentview.com',
    hr_linkedin: 'https://www.linkedin.com/in/geetha-latentview',
    domain: 'Data Science',
    location: 'Chennai / Bengaluru',
    remarks: 'Hold',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },
  {
    id: 'lead_harish_5',
    company_name: 'Sigmoid Analytics',
    website: 'https://sigmoid.com',
    linkedin_url: 'https://www.linkedin.com/company/sigmoid-analytics',
    employee_count: '500-1,000 employees',
    industry: 'Data Engineering & Real-time AI',
    hr_name: 'Rajat Saxena',
    title: 'Senior Technical Recruiter',
    phone: '+91 97170 33819',
    email: 'rajat.s@sigmoid.com',
    hr_linkedin: 'https://www.linkedin.com/in/rajat-saxena-sigmoid',
    domain: 'Gen AI',
    location: 'Bengaluru',
    remarks: 'Responded',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },
  {
    id: 'lead_harish_6',
    company_name: 'Searce Inc',
    website: 'https://searce.com',
    linkedin_url: 'https://www.linkedin.com/company/searce',
    employee_count: '1,000-2,000 employees',
    industry: 'Cloud Engineering & Generative AI Modernization',
    hr_name: 'Aishwarya Patil',
    title: 'Talent Acquisition Partner',
    phone: '+91 98231 99014',
    email: 'aishwarya.p@searce.com',
    hr_linkedin: 'https://www.linkedin.com/in/aishwarya-patil-searce',
    domain: 'Gen AI',
    location: 'Pune / Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Harish',
    entered_by_name: 'Harish Reddy',
  },

  // --- VARSHITH'S SHEET ---
  {
    id: 'lead_varshith_1',
    company_name: 'Persistent Systems',
    website: 'https://persistent.com',
    linkedin_url: 'https://www.linkedin.com/company/persistent-systems',
    employee_count: '10,000+ employees',
    industry: 'Digital Engineering & Enterprise Modernization',
    hr_name: 'Sandeep Phadke',
    title: 'Director - University & Campus Relations',
    phone: '+91 98221 44556',
    email: 'sandeep_phadke@persistent.com',
    hr_linkedin: 'https://www.linkedin.com/in/sandeep-phadke-persistent',
    domain: 'Full Stack',
    location: 'Pune / Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Varshith',
    entered_by_name: 'Varshith Reddy',
  },
  {
    id: 'lead_varshith_2',
    company_name: 'Happiest Minds Technologies',
    website: 'https://happiestminds.com',
    linkedin_url: 'https://www.linkedin.com/company/happiest-minds-technologies',
    employee_count: '5,000-10,000 employees',
    industry: 'Next-Gen IT, IoT & Cloud Development',
    hr_name: 'Anupama Murthy',
    title: 'Associate Vice President - HR',
    phone: '+91 98452 77890',
    email: 'anupama.m@happiestminds.com',
    hr_linkedin: 'https://www.linkedin.com/in/anupama-murthy-happiestminds',
    domain: 'Full Stack',
    location: 'Bengaluru / Pune',
    remarks: 'Responded',
    spoc: 'Varshith',
    entered_by_name: 'Varshith Reddy',
  },
  {
    id: 'lead_varshith_3',
    company_name: 'Birlasoft Ltd',
    website: 'https://birlasoft.com',
    linkedin_url: 'https://www.linkedin.com/company/birlasoft',
    employee_count: '10,000+ employees',
    industry: 'Enterprise Solutions & Cloud Applications',
    hr_name: 'Manish Chawla',
    title: 'Head - Talent Sourcing & Campus Hiring',
    phone: '+91 98118 66230',
    email: 'manish.c@birlasoft.com',
    hr_linkedin: 'https://www.linkedin.com/in/manish-chawla-birlasoft',
    domain: 'Full Stack',
    location: 'Noida / Pune / Bengaluru',
    remarks: 'Hold',
    spoc: 'Varshith',
    entered_by_name: 'Varshith Reddy',
  },
  {
    id: 'lead_varshith_4',
    company_name: 'Mastek Ltd',
    website: 'https://mastek.com',
    linkedin_url: 'https://www.linkedin.com/company/mastek',
    employee_count: '5,000-10,000 employees',
    industry: 'Digital Transformation & Oracle Cloud Apps',
    hr_name: 'Nilesh Ghone',
    title: 'Lead Talent Partner',
    phone: '+91 98205 11980',
    email: 'nilesh.ghone@mastek.com',
    hr_linkedin: 'https://www.linkedin.com/in/nilesh-ghone-mastek',
    domain: 'Full Stack',
    location: 'Mumbai / Pune / Chennai',
    remarks: 'Responded',
    spoc: 'Varshith',
    entered_by_name: 'Varshith Reddy',
  },
  {
    id: 'lead_varshith_5',
    company_name: 'Coforge Ltd',
    website: 'https://coforge.com',
    linkedin_url: 'https://www.linkedin.com/company/coforge-tech',
    employee_count: '10,000+ employees',
    industry: 'Cognitive Computing & Enterprise Cloud',
    hr_name: 'Ritu Agarwal',
    title: 'Senior Manager - Talent Acquisition',
    phone: '+91 98104 33219',
    email: 'ritu.agarwal@coforge.com',
    hr_linkedin: 'https://www.linkedin.com/in/ritu-agarwal-coforge',
    domain: 'Full Stack',
    location: 'Greater Noida / Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Varshith',
    entered_by_name: 'Varshith Reddy',
  },

  // --- AASRITHA'S SHEET ---
  {
    id: 'lead_aasritha_1',
    company_name: 'YASH Technologies',
    website: 'https://yash.com',
    linkedin_url: 'https://www.linkedin.com/company/yash-technologies',
    employee_count: '10,000+ employees',
    industry: 'SAP Implementation, ERP & Cloud Migration',
    hr_name: 'Sunil Sisodiya',
    title: 'Associate Vice President - Global HR',
    phone: '+91 98260 44120',
    email: 'sunil.sisodiya@yash.com',
    hr_linkedin: 'https://www.linkedin.com/in/sunil-sisodiya-yash',
    domain: 'SAP / ERP',
    location: 'Indore / Hyderabad / Pune',
    remarks: 'Responded',
    spoc: 'Aasritha',
    entered_by_name: 'Aasritha K',
  },
  {
    id: 'lead_aasritha_2',
    company_name: 'Bristlecone (Mahindra Group)',
    website: 'https://bcone.com',
    linkedin_url: 'https://www.linkedin.com/company/bristlecone',
    employee_count: '2,000-5,000 employees',
    industry: 'AI Supply Chain & SAP S/4HANA Consulting',
    hr_name: 'Pratibha Shetty',
    title: 'Talent Acquisition Manager',
    phone: '+91 98200 99812',
    email: 'pratibha.s@bcone.com',
    hr_linkedin: 'https://www.linkedin.com/in/pratibha-shetty-bristlecone',
    domain: 'SAP / ERP',
    location: 'Mumbai / Bengaluru / Pune',
    remarks: 'Responded',
    spoc: 'Aasritha',
    entered_by_name: 'Aasritha K',
  },
  {
    id: 'lead_aasritha_3',
    company_name: 'Kaar Technologies',
    website: 'https://kaartech.com',
    linkedin_url: 'https://www.linkedin.com/company/kaar-technologies',
    employee_count: '2,000-5,000 employees',
    industry: 'Pure-play SAP Solutions & Digital Advisory',
    hr_name: 'Venkatesh Babu',
    title: 'Head of Talent Acquisition',
    phone: '+91 98401 55670',
    email: 'venkatesh.b@kaartech.com',
    hr_linkedin: 'https://www.linkedin.com/in/venkatesh-babu-kaar',
    domain: 'SAP / ERP',
    location: 'Chennai / Hyderabad',
    remarks: 'Responded',
    spoc: 'Aasritha',
    entered_by_name: 'Aasritha K',
  },
  {
    id: 'lead_aasritha_4',
    company_name: 'SAVIC Technologies',
    website: 'https://savictech.com',
    linkedin_url: 'https://www.linkedin.com/company/savic-technologies',
    employee_count: '500-1,000 employees',
    industry: 'SAP Gold Partner & Cloud ERP Services',
    hr_name: 'Rupali Jadhav',
    title: 'HR Lead - Campus & Lateral Hiring',
    phone: '+91 98211 44890',
    email: 'rupali.j@savictech.com',
    hr_linkedin: 'https://www.linkedin.com/in/rupali-jadhav-savic',
    domain: 'SAP / ERP',
    location: 'Mumbai / Pune / Bengaluru',
    remarks: 'Hold',
    spoc: 'Aasritha',
    entered_by_name: 'Aasritha K',
  },
  {
    id: 'lead_aasritha_5',
    company_name: 'Tata Technologies Ltd',
    website: 'https://tatatechnologies.com',
    linkedin_url: 'https://www.linkedin.com/company/tata-technologies',
    employee_count: '10,000+ employees',
    industry: 'Automotive & Industrial Engineering Services',
    hr_name: 'Abhay Kulkarni',
    title: 'Global Sourcing & Recruitment Lead',
    phone: '+91 98220 11945',
    email: 'abhay.kulkarni@tatatechnologies.com',
    hr_linkedin: 'https://www.linkedin.com/in/abhay-kulkarni-tatatech',
    domain: 'Full Stack & Embedded',
    location: 'Pune / Bengaluru / Hyderabad',
    remarks: 'Responded',
    spoc: 'Aasritha',
    entered_by_name: 'Aasritha K',
  },

  // --- CHARAN'S SHEET ---
  {
    id: 'lead_charan_1',
    company_name: 'Cyient Ltd',
    website: 'https://cyient.com',
    linkedin_url: 'https://www.linkedin.com/company/cyient',
    employee_count: '10,000+ employees',
    industry: 'Intelligent Engineering & Network Security',
    hr_name: 'Vani Srinivas',
    title: 'Senior Manager - Talent Acquisition',
    phone: '+91 98491 22340',
    email: 'vani.srinivas@cyient.com',
    hr_linkedin: 'https://www.linkedin.com/in/vani-srinivas-cyient',
    domain: 'Cyber Security',
    location: 'Hyderabad / Bengaluru',
    remarks: 'Responded',
    spoc: 'Charan',
    entered_by_name: 'Charan Kumar',
  },
  {
    id: 'lead_charan_2',
    company_name: 'Sonata Software Ltd',
    website: 'https://sonata-software.com',
    linkedin_url: 'https://www.linkedin.com/company/sonata-software',
    employee_count: '5,000-10,000 employees',
    industry: 'Modernization & Enterprise Cloud Development',
    hr_name: 'Ramesh Krishnan',
    title: 'Talent Acquisition Director',
    phone: '+91 98450 44921',
    email: 'ramesh.k@sonata-software.com',
    hr_linkedin: 'https://www.linkedin.com/in/ramesh-krishnan-sonata',
    domain: 'Full Stack',
    location: 'Bengaluru / Hyderabad',
    remarks: 'Responded',
    spoc: 'Charan',
    entered_by_name: 'Charan Kumar',
  },
  {
    id: 'lead_charan_3',
    company_name: 'Apexon (Infostretch)',
    website: 'https://apexon.com',
    linkedin_url: 'https://www.linkedin.com/company/apexon',
    employee_count: '5,000-10,000 employees',
    industry: 'Digital First Engineering & Quality Engineering',
    hr_name: 'Tanvi Shah',
    title: 'Lead Technical Recruiter',
    phone: '+91 98250 33810',
    email: 'tanvi.shah@apexon.com',
    hr_linkedin: 'https://www.linkedin.com/in/tanvi-shah-apexon',
    domain: 'Full Stack',
    location: 'Ahmedabad / Pune / Bengaluru',
    remarks: 'Responded',
    spoc: 'Charan',
    entered_by_name: 'Charan Kumar',
  },
  {
    id: 'lead_charan_4',
    company_name: 'Inspira Enterprise India',
    website: 'https://inspiraenterprise.com',
    linkedin_url: 'https://www.linkedin.com/company/inspira-enterprise',
    employee_count: '1,000-2,000 employees',
    industry: 'Cyber Security & Digital Transformation MSP',
    hr_name: 'Deepa Kamath',
    title: 'Senior HR Manager - Sourcing',
    phone: '+91 98203 77412',
    email: 'deepa.k@inspiraenterprise.com',
    hr_linkedin: 'https://www.linkedin.com/in/deepa-kamath-inspira',
    domain: 'Cyber Security',
    location: 'Mumbai / Pune / Hyderabad',
    remarks: 'Hold',
    spoc: 'Charan',
    entered_by_name: 'Charan Kumar',
  },
  {
    id: 'lead_charan_5',
    company_name: 'Quickhyre AI Labs',
    website: 'https://quickhyre.ai',
    linkedin_url: 'https://www.linkedin.com/company/quickhyre-ai',
    employee_count: '50-100 employees',
    industry: 'Generative AI Candidate Sourcing',
    hr_name: 'Sarath Chandra',
    title: 'Co-Founder & People Lead',
    phone: '+91 98480 33419',
    email: 'sarath@quickhyre.ai',
    hr_linkedin: 'https://www.linkedin.com/in/sarath-chandra-quickhyre',
    domain: 'Gen AI',
    location: 'Hyderabad / Remote',
    remarks: 'Responded',
    spoc: 'Charan',
    entered_by_name: 'Charan Kumar',
  },
];

export const SPOC_MEMBERS = [
  { id: 'Harish', name: 'Harish Reddy', role: 'CRA Specialist', email: 'harish.r@placemein.com', avatarBg: 'bg-purple-600' },
  { id: 'Aravind', name: 'Aravind Reddy', role: 'Founder & CEO (Emp+Admin)', email: 'aravindaravind3953@gmail.com', avatarBg: 'bg-amber-600' },
  { id: 'Charan', name: 'Charan Kumar', role: 'CRA Specialist (Emp+Admin)', email: 'charankumar.n@placemein.com', avatarBg: 'bg-teal-600' },
  { id: 'Mrudula', name: 'Mrudula', role: 'CRA Specialist', email: 'mrudula.k@placemein.com', avatarBg: 'bg-pink-600' },
  { id: 'Namitha', name: 'Namitha K', role: 'CRA Specialist', email: 'namitha.k@placemein.com', avatarBg: 'bg-emerald-600' },
  { id: 'Solomon', name: 'Solomon Raj', role: 'CRA Specialist', email: 'solomon.r@placemein.com', avatarBg: 'bg-blue-600' },
  { id: 'Vineela', name: 'Vineela Bathula', role: 'Manager & Talent Partner', email: 'vineela.b@placemein.com', avatarBg: 'bg-indigo-700' },
  { id: 'Mansi', name: 'Mansi Ramesh Peddi', role: 'CRA Team Lead & Verification Head', email: 'mansi.p@placemein.com', avatarBg: 'bg-purple-700' },
];
